# Uva Province {#sec-intro}

```{r}
#| label: load_packages
#| include: false
library(dplyr)
library(ggplot2)
library(lubridate)
library(ditwahLandslide)
```

## Badulla

### Warning Release Time

```{r, out.height="100%", echo=FALSE}
# create datetime variable
ditwah_landslides_warnings2 <- ditwah_landslides_warnings |>
  mutate(
    valid_from_dt = ymd_hm(
      paste(Valid_From_Date, Valid_From_Time)
    )
  )

p1 <- ditwah_landslides_warnings2 |>
  mutate(Level = as.factor(Level)) |>
 filter(Province == "Uva") |>
  filter(District == "Badulla") |>
ggplot(aes(x = Valid_From_Date,
           y = Location,
fill = Level)) +
  geom_tile(color = "white") +
  scale_fill_manual(values = c("#FFFF00", "#D79334", "red"))
  labs(
    x = "Valid From (Date-Time)",
    y = "Location",
    fill = "Warning Level") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank() 
  )
p1
```


```{r, , out.height="100%"}
# install.packages("pak")
#pak::pak("thiyangt/ditwahLandslide")
library(ditwahLandslide)
viz_landslide_warnings_from_to(province = "Uva", district = "Badulla", interactivity=FALSE)
```


## Monaragala
